#!/usr/bin/env python3

from synonyms import synonyms

class teams(synonyms):

    def __init__(self):

        super().__init__()

        self.log = open('.team_synonyms.log', 'a')

        #Paris Saint Germain

        self.synonym_list = {
            '1860 Munich'           : '1860 Munchen',
            'Accrington Stanley'    : 'Accrington',
            'Ajaccio GFCO'          : 'Ajaccio',
            'Albion R'              : 'Albion',
            'Alloa Athletic'        : 'Alloa',
            'Ascoli Picchio 1898'   : 'Ascoli',
            'Atalanta Bergamasca Calcio' : 'Atalanta',
            'Athletic B'            : 'Athletic Club Bilbao',
            'Athletic Bilbao'       : 'Athletic Club Bilbao',
            'Atlas De Guadalajara'  : 'Atlas',
            'Ayr United'            : 'Ayr',
            'Atromitos Athinon'     : 'Atromitos',
            'Avellino Calcio 1912'  : 'Avellino',
            'Blackburn Rovers'      : 'Blackburn',
            'Berwick Rangers'       : 'Berwick',
            'Biel Bienne'           : 'Biel',
            'Boavista Porto'        : 'Boavista',
            'Bourg en Bresse Peronnas' : 'Bourg Peronnas',
            'Bradford Park Avenue'  : 'Bradford',
            'Bohemians 1905'        : 'Bohemians',
            'Bradford City'         : 'Bradford',
            'Brighton & Hove Albion': 'Brighton',
            'Cambridge United'      : 'Cambridge',
            'Cambridge Utd'         : 'Cambridge',
            'Cambuur Leeuwarden'    : 'Cambuur',
            'Cardiff City'          : 'Cardiff',
            'Charlton Athletic'     : 'Charlton',
            'Chelmsford City'       : 'Chelmsford',
            'Chievo Verona'         : 'Chievo',
            'Colchester United'     : 'Colchester',
            'Darmstadt 98'          : 'Darmstadt',
            'Dag & Redbridge'       : 'Dag & Red',
            'Degerfors IF'          : 'Degerfors',
            'Derby County'          : 'Derby',
            'Doncaster Rovers'      : 'Doncaster',
            'Dorados De Sinaloa'    : 'Dorados',
            'Dinamo Bucuresti'      : 'Dinamo Bucharest',
            'Dynamo Kyiv'           : 'Dynamo Kiev',
            'East Stirlingshire'    : 'East Stirling',
            'Evian Thonon Gaillard' : 'Evian',
            'Excelsior Rotterdam'   : 'Excelsior',
            'Forest Green Rovers'   : 'Forest Green',
            'Frosinone Calcio'      : 'Frosinone',
            'FSV Mainz 05'          : 'Mainz',
            'FSV Mainz 05 II'       : 'Mainz II',
            'Gainsborough Trinity'  : 'Gainsborough',
            'Grasshopper Zurich'    : 'Grasshoppers',
            'Hertha BSC Berlin'     : 'Hertha Berlin',
            'IK Sirius FK'          : 'Sirius',
            'Ingolstadt 04'         : 'Ingolstadt',
            'Istra 1961'            : 'Istra',
            'Jaguares de Chiapas'   : 'Jaguares Chiapas',
            'Jong PSV Eindhoven'    : 'Jong PSV',
            'Kidderminster Harriers': 'Kidderminster',
            'Kobenhavn'             : 'Kopenhamn',
            'Lausanne Sport'        : 'Lausanne',
            'Leicester City'        : 'Leicester',
            'Lincoln City'          : 'Lincoln',
            'Milton Keynes Dons'    : 'Milton Keynes',
            'Norwich City'          : 'Norwich',
            'Oldham Athletic'       : 'Oldham',
            'Olympiakos Piraeus'    : 'Olympiakos',
            'Pacos de Ferreira'     : 'Pacos Ferreira',
            'Paris SG'              : 'PSG',
            'Paris Saint Germain'   : 'PSG',
            'Partick Thistle'       : 'Partick',
            'Peterborough United'   : 'Peterborough',
            'Perugia Calcio Spa'    : 'Perugia',
            'Plymouth Argyle'       : 'Plymouth',
            'Preston North End'     : 'Preston',
            'Pro Vercelli 1892'     : 'Pro Vercelli',
            'Queen Of The South'    : 'Queen of South',
            'Queens Park Rangers FC': 'QPR',
            'Queens Park Rangers'   : 'QPR',
            'Rotherham United'      : 'Rotherham',
            'Sheffield Wednesday'   : 'Sheffield Wed',
            'Sheff Wed'             : 'Sheffield Wed',
            'Sheff U'               : 'Sheffield U',
            'Sirius FK'             : 'Sirius',
            'Sparta Prague'         : 'Sparta Prag',
            'Stalybridge Celtic'    : 'Stalybridge',
            'Stoke City'            : 'Stoke',
            'Swansea City'          : 'Swansea',
            'Tottenham Hotspur'     : 'Tottenham',
            'Torquay United'        : 'Torquay',
            'Twente Enschede'       : 'Twente',
            'Varbergs BoIS FC'      : 'Varberg',
            'West Bromwich'         : 'West Brom',
            'Zenit St Petersburg'   : 'Zenit',
            'Zenit StPetersburg'    : 'Zenit',
            'York City'             : 'York'}

        self.prefixes = [
                ('AA '          , ''),
                ('AC '          , ''),
                ('AD '          , ''),
                ('ADO '         , ''),
                ('AEP '         , ''),
                ('AJ '          , ''),
                ('AFC '         , ''),
                ('BK '          , ''),
                ('CD '          , ''),
                ('CF '          , ''),
                ('CFR '         , ''),
                ('CSU '         , ''),
                ('Borussia '    , ''),
                ('FBC '         , ''),
                ('FC '          , ''),
                ('FCB '         , ''),
                ('FCM '         , ''),
                ('FK '          , ''),
                ('FSV '         , ''),
                ('GIF '         , ''),
                ('IF '          , ''),
                ('IFK '         , ''),
                ('IK '          , ''),
                ('KV '          , ''),
                ('HNK '         , ''),
                ('KAA '         , ''),
                ('NK '          , ''),
                ('PAOK '        , ''),
                ('PAS '         , ''),
                ('PEC '         , ''),
                ('RB '          , ''),
                ('RNK '         , ''),
                ('RKC '         , ''),
                ('RC '          , ''),
                ('RJ '          , ''),
                ('SC '          , ''),
                ('SG '          , ''),
                ('SK '          , ''),
                ('SV '          , ''),
                ('TSG '         , ''),
                ('VfB '         , ''),
                ('VfL '         , ''),
                ('VfR '         , '')]

        self.suffixes = [
                ('s BK'         , ''),
                ('s BoIS'       , ''),
                ('s IF'         , ''),
                ('s FF'         , ''),
                ('s FK'         , ''),
                (' AC'          , ''),
                (' AD'          , ''),
                (' AFC'         , ''),
                (' Am'          , ''),
                (' AS'          , ''),
                (' BoIS'        , ''),
                (' BC'          , ''),
                (' BK'          , ''),
                (' CD'          , ''),
                (' CF'          , ''),
                (' IF'          , ''),
                (' IS'          , ''),
                (' FB'          , ''),
                (' FF'          , ''),
                (' FK'          , ''),
                (' FC'          , ''),
                (' Foren'       , ''),
                (' GS'          , ''),
                (' GF'          , ''),
                (' JC'          , ''),
                (' LS'          , ''),
                (' RJ'          , ''),
                (' SC'          , ''),
                (' SK'          , ''),
                (' Town'        , ''),
                (' United'      , ' U'),
                (' Utd'         , ' U'),
                (' Unidos'      , ' U')]
