#!/usr/bin/env python3

from synonyms import synonyms

class teams(synonyms):

    def __init__(self):

        super().__init__()

        self.log = open('.team_synonyms.log', 'a')

        self.synonym_list = {
            '1 FC Nurnberg'             : 'Nurnberg',
            '1 FC Koln'                 : 'Koln',
            '1860 Munich'               : '1860 Munchen',
            'Aalborg BK'                : 'Alborg',
            'Accrington Stanley'        : 'Accrington',
            'AC Chievo Verona'          : 'Chievo',
            'AGF'                       : 'Arhus',
            'Ajaccio GFCO'              : 'Ajaccio',
            'Albion R'                  : 'Albion',
            'Alloa Athletic'            : 'Alloa',
            'Ascoli Picchio 1898'       : 'Ascoli',
            'Atalanta Bergamasca Calcio': 'Atalanta',
            'Athletic B'                : 'Athletic Club Bilbao',
            'Athletic Bilbao'           : 'Athletic Club Bilbao',
            'AFC United'                : 'Athletic FC U',
            'Atlas De Guadalajara'      : 'Atlas',
            'Ayr United'                : 'Ayr',
            'Atromitos Athinon'         : 'Atromitos',
            'Avellino Calcio 1912'      : 'Avellino',
            'Blackburn Rovers'          : 'Blackburn',
            'Berwick Rangers'           : 'Berwick',
            'Biel Bienne'               : 'Biel',
            'Birmingham City'           : 'Birmingham',
            'Boavista Porto'            : 'Boavista',
            'Bourg en Bresse Peronnas'  : 'Bourg Peronnas',
            'Bradford Park Avenue'      : 'Bradford',
            'Bradford City'             : 'Bradford',
            'Brighton & Hove Albion'    : 'Brighton',
            'Burton Albion'             : 'Burton',
            'Cambridge United'          : 'Cambridge',
            'Cambridge Utd'             : 'Cambridge',
            'Cambuur Leeuwarden'        : 'Cambuur',
            'Cardiff City'              : 'Cardiff',
            'Caykur Rizespor'           : 'Rizespor',
            'Charlton Athletic'         : 'Charlton',
            'Chelmsford City'           : 'Chelmsford',
            'Chievo Verona'             : 'Chievo',
            'Colchester United'         : 'Colchester',
            'Dag & Redbridge'           : 'Dag & Red',
            'Degerfors IF'              : 'Degerfors',
            'Deportes Antofagasta'      : 'Antofagasta',
            'Derby County'              : 'Derby',
            'Doncaster Rovers'          : 'Doncaster',
            'Dorados De Sinaloa'        : 'Dorados',
            'Dinamo Bucuresti'          : 'Dinamo Bucharest',
            'Dynamo Kyiv'               : 'Dynamo Kiev',
            'East Stirlingshire'        : 'East Stirling',
            'Evian Thonon Gaillard'     : 'Evian',
            'Excelsior Rotterdam'       : 'Excelsior',
            'FC København'              : 'Kobenhavn',
            'Veroia Fc'                 : 'Veria',
            'Forest Green Rovers'       : 'Forest Green',
            'Forfar Athletic'           : 'Forfar',
            'Frosinone Calcio'          : 'Frosinone',
            'FSV Mainz 05 II'           : 'Mainz II',
            'Gainsborough Trinity'      : 'Gainsborough',
            'Genclerbirligi Ankara'     : 'Genclerbirligi',
            'Grasshopper Zurich'        : 'Grasshoppers',
            'Hamburger SV'              : 'Hamburg',
            'Hellas Verona'             : 'Verona',
            'Hertha BSC Berlin'         : 'Hertha Berlin',
            'Hull City'                 : 'Hull',
            'IK Sirius FK'              : 'Sirius',
            'Jaguares de Chiapas'       : 'Jaguares Chiapas',
            'Jong PSV Eindhoven'        : 'Jong PSV',
            'Kidderminster Harriers'    : 'Kidderminster',
            'Kobenhavn'                 : 'Kopenhamn',
            'Lausanne Sport'            : 'Lausanne',
            'Leicester City'            : 'Leicester',
            'Leeds United'              : 'Leeds',
            'Lincoln City'              : 'Lincoln',
            'Lokomotiv Moscow'          : 'Lokomotiv Moskva',
            'Milton Keynes Dons'        : 'Milton Keynes',
            'NE Xamax'                  : 'Neuchatel Xamax',
            'Norwich City'              : 'Norwich',
            'Oldham Athletic'           : 'Oldham',
            'Olympiakos Piraeus'        : 'Olympiakos',
            'Olympique Nimes'           : 'Nimes',
            'Pacos de Ferreira'         : 'Pacos Ferreira',
            'Paris SG'                  : 'PSG',
            'Paris Saint Germain'       : 'PSG',
            'Partick Thistle'           : 'Partick',
            'Peterborough United'       : 'Peterborough',
            'Perugia Calcio Spa'        : 'Perugia',
            'Plymouth Argyle'           : 'Plymouth',
            'Preston North End'         : 'Preston',
            'Queen Of The South'        : 'Queen of South',
            'Queens Park Rangers FC'    : 'QPR',
            'Queens Park Rangers'       : 'QPR',
            'Rotherham United'          : 'Rotherham',
            'Sheffield Wednesday'       : 'Sheffield Wed',
            'Sheff Wed'                 : 'Sheffield Wed',
            'Sheff U'                   : 'Sheffield U',
            'Sirius FK'                 : 'Sirius',
            'Sparta Prague'             : 'Sparta Prag',
            'Sparta Praha'              : 'Sparta Prag',
            'Stade Reims'               : 'Reims',
            'Stalybridge Celtic'        : 'Stalybridge',
            'Steaua Bucharest'          : 'Steaua Bukarest',
            'Stoke City'                : 'Stoke',
            'Swansea City'              : 'Swansea',
            'Sporting CP'               : 'Sporting',
            'Sporting Lisbon'           : 'Sporting',
            'Sporting Braga'            : 'Braga',
            'Tottenham Hotspur'         : 'Tottenham',
            'Torquay United'            : 'Torquay',
            'Trapani Calcio'            : 'Trapani',
            'Twente Enschede'           : 'Twente',
            'Universidad Cesar Vallejo' : 'Cesar Vallejo',
            'Varbergs BoIS FC'          : 'Varberg',
            'Veroia'                    : 'Veria',
            'West Bromwich'             : 'West Brom',
            'Welling United'            : 'Welling',
            'Wolves'                    : 'Wolverhampton Wanderers',
            'Zenit St Petersburg'       : 'Zenit',
            'Zenit StPetersburg'        : 'Zenit',
            'York City'                 : 'York'}

        self.prefixes = [
                ('AA '          , ''),
                ('AC '          , ''),
                ('AD '          , ''),
                ('ADO '         , ''),
                ('AEP '         , ''),
                ('AJ '          , ''),
                ('AFC '         , ''),
                ('BK '          , ''),
                ('CD '          , ''),
                ('CF '          , ''),
                ('CFR '         , ''),
                ('CSU '         , ''),
                ('Borussia '    , ''),
                ('FBC '         , ''),
                ('FC '          , ''),
                ('FCB '         , ''),
                ('FCM '         , ''),
                ('FK '          , ''),
                ('FSV '         , ''),
                ('GIF '         , ''),
                ('IF '          , ''),
                ('IFK '         , ''),
                ('IK '          , ''),
                ('KV '          , ''),
                ('HNK '         , ''),
                ('KAA '         , ''),
                ('NK '          , ''),
                ('PAOK '        , ''),
                ('PAS '         , ''),
                ('PEC '         , ''),
                ('RB '          , ''),
                ('RNK '         , ''),
                ('RKC '         , ''),
                ('RC '          , ''),
                ('RJ '          , ''),
                ('SC '          , ''),
                ('SG '          , ''),
                ('SK '          , ''),
                ('SV '          , ''),
                ('TSG '         , ''),
                ('VfB '         , ''),
                ('VfL '         , ''),
                ('VfR '         , '')]

        self.suffixes = [
                ('s BK'         , ''),
                ('s BoIS'       , ''),
                ('s IF'         , ''),
                ('s FF'         , ''),
                ('s FK'         , ''),
                (' AC'          , ''),
                (' AD'          , ''),
                (' AFC'         , ''),
                (' Am'          , ''),
                (' AS'          , ''),
                (' BoIS'        , ''),
                (' BC'          , ''),
                (' BK'          , ''),
                (' CD'          , ''),
                (' CF'          , ''),
                (' IF'          , ''),
                (' IK'          , ''),
                (' IS'          , ''),
                (' FB'          , ''),
                (' FF'          , ''),
                (' FK'          , ''),
                (' FC'          , ''),
                (' Foren'       , ''),
                (' GS'          , ''),
                (' GF'          , ''),
                (' JC'          , ''),
                (' LS'          , ''),
                (' RJ'          , ''),
                (' SC'          , ''),
                (' SK'          , ''),
                (' Town'        , ''),
                (' United'      , ' U'),
                (' Utd'         , ' U'),
                (' Unidos'      , ' U')]
